export const CHAT_TEXT = "TEXT";
export const CHAT_IMAGE = "IMAGE";
export const CHAT_SCENARIO = "SCENARIO";
export const CHAT_WARNING = "WARNING";
export const CHAT_CALL_ATTEMPT = "CALL_ATTEMPT";
export const CHAT_CALL_COMPLETED = "CALL_COMPLETED";

export const SCENARIO_FREQUENTLY_ASKED = "FREQUENTLY_ASKED_MESSAGE";

export const SCENARIO_TEXT_API_BUTTON = "TEXT_API_BUTTON";
export const SCENARIO_TEXT_URL_BUTTON = "TEXT_URL_BUTTON";
export const SCENARIO_TEXT_NAVIGATE_BUTTON = "TEXT_NAVIGATE_BUTTON";
