export const LICENSE_TYPE_INDIVIDUAL_SMALL = "INDIVIDUAL_SMALL";
export const LICENSE_TYPE_INDIVIDUAL_MIDDLE = "INDIVIDUAL_MIDDLE";
export const LICENSE_TYPE_INDIVIDUAL_HIGH = "INDIVIDUAL_HIGH";
export const LICENSE_TYPE_INDIVIDUAL_DELIVERY = "INDIVIDUAL_DELIVERY";

export const INDIVIDUAL_LICENSE_TYPE_CODES = [
  LICENSE_TYPE_INDIVIDUAL_SMALL,
  LICENSE_TYPE_INDIVIDUAL_MIDDLE,
  LICENSE_TYPE_INDIVIDUAL_HIGH,
  LICENSE_TYPE_INDIVIDUAL_DELIVERY,
] as const;
